name: wavelet-logic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - ptwt
      - PyWavelets
      - datasets
      - transformers
      - accelerate
      - python-dotenv
